# Generated by Django 5.1.6 on 2025-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_record_updated_alter_record_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='freetime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='productivity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='worktime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='states',
            field=models.ManyToManyField(blank=True, to='api.state'),
        ),
    ]
